### ISSUE TITLE
[TOPIC] Workspace

### ISSUE THREAD

**Issue by Yehonal** [AzerothShard/ASApp#3]
E' stato creato un workspace su cloud9 , facendo richiesta di collaborazione è possibile lavorare in remoto al progetto senza bisogno di altro:

https://ide.c9.io/yehonal/as-app

A disposizione di chi vuole provare

_P.S. Questo è anche un esperimento di creazione "topic" tramite le issue di github, in modo tale da non dover ricorrere anche ad un forum dedicato. Basta impostare le label "topic" o "topic-pinned"_

**Comment by waliente** [comment]
Ciao Bello io staro fuori fino a domenica. Lunedi do un occhiata alle mail.

Per quello che riguarda il lazyloading del css non ne capisco l utilita
visto ke usando sass si compila un .css tutto minificato.

Cmq non conosco una tecnica angular che permetta di fare cio. Ma so che
esiste yepnope o requirejs... Bisogna vedere un po...

Saluti
Il 29/giu/2016 19:35, "Yehonal" notifications@github.com ha scritto:

Closed #3 https://github.com/AzerothShard/ASApp/issues/3.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/AzerothShard/ASApp/issues/3#event-708095309, or mute
the thread
https://github.com/notifications/unsubscribe/ASsxT_ziV6BABGRNeQNC44dgci_LQobNks5qQqzbgaJpZM4JBYWG
.

**Comment by Yehonal** [comment]
ciao @waliente ! 

Va bene tranquillo :) intanto stiamo procedendo con delle modifiche. Comunque il lazyloading del js e del css verrà fatto tramite un plugin per angular che sto scrivendo che sfrutterà anche requirejs si.

Non servirà strettamente a noi, ma a caricare i moduli "arena stats" , "server status" ecc dinamicamente tramite una struttura "a componenti" anzichè tramite iframe. Pertanto invierò una PR a quei progetti per adattarli.

Puoi tranquillamente sviluppare il template dell'app utilizzando sass come dicevi.

**Comment by darioTecchia** [comment]
Ho provato ad usare `ng-include` al posto dell'iframe ma ovviamente da problemi di Same Origin Policy.
